//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEnPA.senpaSecurity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool authenticationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int responseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.accessTokenField, value) != true)) {
                    this.accessTokenField = value;
                    this.RaisePropertyChanged("accessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool authenticationStatus {
            get {
                return this.authenticationStatusField;
            }
            set {
                if ((this.authenticationStatusField.Equals(value) != true)) {
                    this.authenticationStatusField = value;
                    this.RaisePropertyChanged("authenticationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                if ((this.responseCodeField.Equals(value) != true)) {
                    this.responseCodeField = value;
                    this.RaisePropertyChanged("responseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignoutResponse", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class SignoutResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool signoutStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool signoutStatus {
            get {
                return this.signoutStatusField;
            }
            set {
                if ((this.signoutStatusField.Equals(value) != true)) {
                    this.signoutStatusField = value;
                    this.RaisePropertyChanged("signoutStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordChangeResponse", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class PasswordChangeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool changeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool changeStatus {
            get {
                return this.changeStatusField;
            }
            set {
                if ((this.changeStatusField.Equals(value) != true)) {
                    this.changeStatusField = value;
                    this.RaisePropertyChanged("changeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRoleActionResponse", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class UserRoleActionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool actionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool actionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                if ((this.actionStatusField.Equals(value) != true)) {
                    this.actionStatusField = value;
                    this.RaisePropertyChanged("actionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserActionResponse", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class UserActionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool actionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool actionStatus {
            get {
                return this.actionStatusField;
            }
            set {
                if ((this.actionStatusField.Equals(value) != true)) {
                    this.actionStatusField = value;
                    this.RaisePropertyChanged("actionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage {
            get {
                return this.responseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMessageField, value) != true)) {
                    this.responseMessageField = value;
                    this.RaisePropertyChanged("responseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationUsers", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class ApplicationUsers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PasswordExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PasswordExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PasswordLastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy {
            get {
                return this.LastModifiedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LastModifiedByField, value) != true)) {
                    this.LastModifiedByField = value;
                    this.RaisePropertyChanged("LastModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Locked {
            get {
                return this.LockedField;
            }
            set {
                if ((this.LockedField.Equals(value) != true)) {
                    this.LockedField = value;
                    this.RaisePropertyChanged("Locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passcode {
            get {
                return this.PasscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PasscodeField, value) != true)) {
                    this.PasscodeField = value;
                    this.RaisePropertyChanged("Passcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PasswordExpires {
            get {
                return this.PasswordExpiresField;
            }
            set {
                if ((this.PasswordExpiresField.Equals(value) != true)) {
                    this.PasswordExpiresField = value;
                    this.RaisePropertyChanged("PasswordExpires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PasswordExpiryDate {
            get {
                return this.PasswordExpiryDateField;
            }
            set {
                if ((this.PasswordExpiryDateField.Equals(value) != true)) {
                    this.PasswordExpiryDateField = value;
                    this.RaisePropertyChanged("PasswordExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PasswordLastChanged {
            get {
                return this.PasswordLastChangedField;
            }
            set {
                if ((this.PasswordLastChangedField.Equals(value) != true)) {
                    this.PasswordLastChangedField = value;
                    this.RaisePropertyChanged("PasswordLastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleGroup {
            get {
                return this.RoleGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleGroupField, value) != true)) {
                    this.RoleGroupField = value;
                    this.RaisePropertyChanged("RoleGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationRoles", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class ApplicationRoles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationRoleGroups", Namespace="http://schemas.datacontract.org/2004/07/SEnPA")]
    [System.SerializableAttribute()]
    public partial class ApplicationRoleGroups : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleGroupIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleGroup {
            get {
                return this.RoleGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleGroupField, value) != true)) {
                    this.RoleGroupField = value;
                    this.RaisePropertyChanged("RoleGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleGroupId {
            get {
                return this.RoleGroupIdField;
            }
            set {
                if ((this.RoleGroupIdField.Equals(value) != true)) {
                    this.RoleGroupIdField = value;
                    this.RaisePropertyChanged("RoleGroupId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="senpaSecurity.ISEnPASecurity")]
    public interface ISEnPASecurity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/Authenticate", ReplyAction="http://tempuri.org/ISEnPASecurity/AuthenticateResponse")]
        SEnPA.senpaSecurity.AuthenticationResponse Authenticate(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/Authenticate", ReplyAction="http://tempuri.org/ISEnPASecurity/AuthenticateResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.AuthenticationResponse> AuthenticateAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/Signout", ReplyAction="http://tempuri.org/ISEnPASecurity/SignoutResponse")]
        SEnPA.senpaSecurity.SignoutResponse Signout(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/Signout", ReplyAction="http://tempuri.org/ISEnPASecurity/SignoutResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.SignoutResponse> SignoutAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/ChangePassword", ReplyAction="http://tempuri.org/ISEnPASecurity/ChangePasswordResponse")]
        SEnPA.senpaSecurity.PasswordChangeResponse ChangePassword(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/ChangePassword", ReplyAction="http://tempuri.org/ISEnPASecurity/ChangePasswordResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.PasswordChangeResponse> ChangePasswordAsync(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddRole", ReplyAction="http://tempuri.org/ISEnPASecurity/AddRoleResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse AddRole(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddRole", ReplyAction="http://tempuri.org/ISEnPASecurity/AddRoleResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddRoleAsync(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/RemoveRole", ReplyAction="http://tempuri.org/ISEnPASecurity/RemoveRoleResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse RemoveRole(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/RemoveRole", ReplyAction="http://tempuri.org/ISEnPASecurity/RemoveRoleResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> RemoveRoleAsync(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddUser", ReplyAction="http://tempuri.org/ISEnPASecurity/AddUserResponse")]
        SEnPA.senpaSecurity.UserActionResponse AddUser(string username, string password, string roleGroup, string firstName, string surname, string emailAddress, string mobileNumber, bool passwordExpires, bool active, bool locked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddUser", ReplyAction="http://tempuri.org/ISEnPASecurity/AddUserResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserActionResponse> AddUserAsync(string username, string password, string roleGroup, string firstName, string surname, string emailAddress, string mobileNumber, bool passwordExpires, bool active, bool locked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/UpdateUser", ReplyAction="http://tempuri.org/ISEnPASecurity/UpdateUserResponse")]
        SEnPA.senpaSecurity.UserActionResponse UpdateUser(string username, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/UpdateUser", ReplyAction="http://tempuri.org/ISEnPASecurity/UpdateUserResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserActionResponse> UpdateUserAsync(string username, string action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetUsers", ReplyAction="http://tempuri.org/ISEnPASecurity/GetUsersResponse")]
        SEnPA.senpaSecurity.ApplicationUsers[] GetUsers(string filterText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetUsers", ReplyAction="http://tempuri.org/ISEnPASecurity/GetUsersResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationUsers[]> GetUsersAsync(string filterText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetUser", ReplyAction="http://tempuri.org/ISEnPASecurity/GetUserResponse")]
        SEnPA.senpaSecurity.ApplicationUsers GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetUser", ReplyAction="http://tempuri.org/ISEnPASecurity/GetUserResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationUsers> GetUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetApplicationRoles", ReplyAction="http://tempuri.org/ISEnPASecurity/GetApplicationRolesResponse")]
        SEnPA.senpaSecurity.ApplicationRoles[] GetApplicationRoles(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetApplicationRoles", ReplyAction="http://tempuri.org/ISEnPASecurity/GetApplicationRolesResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationRoles[]> GetApplicationRolesAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/AddGroupRoleResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse AddGroupRole(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/AddGroupRoleResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddGroupRoleAsync(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/RemoveGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/RemoveGroupRoleResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse RemoveGroupRole(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/RemoveGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/RemoveGroupRoleResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> RemoveGroupRoleAsync(string username, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetApplicationGroupRoles", ReplyAction="http://tempuri.org/ISEnPASecurity/GetApplicationGroupRolesResponse")]
        SEnPA.senpaSecurity.ApplicationRoleGroups[] GetApplicationGroupRoles(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetApplicationGroupRoles", ReplyAction="http://tempuri.org/ISEnPASecurity/GetApplicationGroupRolesResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationRoleGroups[]> GetApplicationGroupRolesAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddUserGroup", ReplyAction="http://tempuri.org/ISEnPASecurity/AddUserGroupResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse AddUserGroup(string group, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddUserGroup", ReplyAction="http://tempuri.org/ISEnPASecurity/AddUserGroupResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddUserGroupAsync(string group, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetApplicationUserGroupRoles", ReplyAction="http://tempuri.org/ISEnPASecurity/GetApplicationUserGroupRolesResponse")]
        SEnPA.senpaSecurity.ApplicationRoles[] GetApplicationUserGroupRoles(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/GetApplicationUserGroupRoles", ReplyAction="http://tempuri.org/ISEnPASecurity/GetApplicationUserGroupRolesResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationRoles[]> GetApplicationUserGroupRolesAsync(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddUserGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/AddUserGroupRoleResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse AddUserGroupRole(string group, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/AddUserGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/AddUserGroupRoleResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddUserGroupRoleAsync(string group, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/RemoveUserGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/RemoveUserGroupRoleResponse")]
        SEnPA.senpaSecurity.UserRoleActionResponse RemoveUserGroupRole(string group, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/RemoveUserGroupRole", ReplyAction="http://tempuri.org/ISEnPASecurity/RemoveUserGroupRoleResponse")]
        System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> RemoveUserGroupRoleAsync(string group, string userRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/DefaultPassword", ReplyAction="http://tempuri.org/ISEnPASecurity/DefaultPasswordResponse")]
        string DefaultPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISEnPASecurity/DefaultPassword", ReplyAction="http://tempuri.org/ISEnPASecurity/DefaultPasswordResponse")]
        System.Threading.Tasks.Task<string> DefaultPasswordAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISEnPASecurityChannel : SEnPA.senpaSecurity.ISEnPASecurity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SEnPASecurityClient : System.ServiceModel.ClientBase<SEnPA.senpaSecurity.ISEnPASecurity>, SEnPA.senpaSecurity.ISEnPASecurity {
        
        public SEnPASecurityClient() {
        }
        
        public SEnPASecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SEnPASecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SEnPASecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SEnPASecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SEnPA.senpaSecurity.AuthenticationResponse Authenticate(string username, string password) {
            return base.Channel.Authenticate(username, password);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.AuthenticationResponse> AuthenticateAsync(string username, string password) {
            return base.Channel.AuthenticateAsync(username, password);
        }
        
        public SEnPA.senpaSecurity.SignoutResponse Signout(string username) {
            return base.Channel.Signout(username);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.SignoutResponse> SignoutAsync(string username) {
            return base.Channel.SignoutAsync(username);
        }
        
        public SEnPA.senpaSecurity.PasswordChangeResponse ChangePassword(string username, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(username, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.PasswordChangeResponse> ChangePasswordAsync(string username, string oldPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(username, oldPassword, newPassword);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse AddRole(string username, string userRole) {
            return base.Channel.AddRole(username, userRole);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddRoleAsync(string username, string userRole) {
            return base.Channel.AddRoleAsync(username, userRole);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse RemoveRole(string username, string userRole) {
            return base.Channel.RemoveRole(username, userRole);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> RemoveRoleAsync(string username, string userRole) {
            return base.Channel.RemoveRoleAsync(username, userRole);
        }
        
        public SEnPA.senpaSecurity.UserActionResponse AddUser(string username, string password, string roleGroup, string firstName, string surname, string emailAddress, string mobileNumber, bool passwordExpires, bool active, bool locked) {
            return base.Channel.AddUser(username, password, roleGroup, firstName, surname, emailAddress, mobileNumber, passwordExpires, active, locked);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserActionResponse> AddUserAsync(string username, string password, string roleGroup, string firstName, string surname, string emailAddress, string mobileNumber, bool passwordExpires, bool active, bool locked) {
            return base.Channel.AddUserAsync(username, password, roleGroup, firstName, surname, emailAddress, mobileNumber, passwordExpires, active, locked);
        }
        
        public SEnPA.senpaSecurity.UserActionResponse UpdateUser(string username, string action) {
            return base.Channel.UpdateUser(username, action);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserActionResponse> UpdateUserAsync(string username, string action) {
            return base.Channel.UpdateUserAsync(username, action);
        }
        
        public SEnPA.senpaSecurity.ApplicationUsers[] GetUsers(string filterText) {
            return base.Channel.GetUsers(filterText);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationUsers[]> GetUsersAsync(string filterText) {
            return base.Channel.GetUsersAsync(filterText);
        }
        
        public SEnPA.senpaSecurity.ApplicationUsers GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationUsers> GetUserAsync(string username) {
            return base.Channel.GetUserAsync(username);
        }
        
        public SEnPA.senpaSecurity.ApplicationRoles[] GetApplicationRoles(string username) {
            return base.Channel.GetApplicationRoles(username);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationRoles[]> GetApplicationRolesAsync(string username) {
            return base.Channel.GetApplicationRolesAsync(username);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse AddGroupRole(string username, string userRole) {
            return base.Channel.AddGroupRole(username, userRole);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddGroupRoleAsync(string username, string userRole) {
            return base.Channel.AddGroupRoleAsync(username, userRole);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse RemoveGroupRole(string username, string userRole) {
            return base.Channel.RemoveGroupRole(username, userRole);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> RemoveGroupRoleAsync(string username, string userRole) {
            return base.Channel.RemoveGroupRoleAsync(username, userRole);
        }
        
        public SEnPA.senpaSecurity.ApplicationRoleGroups[] GetApplicationGroupRoles(string username) {
            return base.Channel.GetApplicationGroupRoles(username);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationRoleGroups[]> GetApplicationGroupRolesAsync(string username) {
            return base.Channel.GetApplicationGroupRolesAsync(username);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse AddUserGroup(string group, string description) {
            return base.Channel.AddUserGroup(group, description);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddUserGroupAsync(string group, string description) {
            return base.Channel.AddUserGroupAsync(group, description);
        }
        
        public SEnPA.senpaSecurity.ApplicationRoles[] GetApplicationUserGroupRoles(string group) {
            return base.Channel.GetApplicationUserGroupRoles(group);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.ApplicationRoles[]> GetApplicationUserGroupRolesAsync(string group) {
            return base.Channel.GetApplicationUserGroupRolesAsync(group);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse AddUserGroupRole(string group, string userRole) {
            return base.Channel.AddUserGroupRole(group, userRole);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> AddUserGroupRoleAsync(string group, string userRole) {
            return base.Channel.AddUserGroupRoleAsync(group, userRole);
        }
        
        public SEnPA.senpaSecurity.UserRoleActionResponse RemoveUserGroupRole(string group, string userRole) {
            return base.Channel.RemoveUserGroupRole(group, userRole);
        }
        
        public System.Threading.Tasks.Task<SEnPA.senpaSecurity.UserRoleActionResponse> RemoveUserGroupRoleAsync(string group, string userRole) {
            return base.Channel.RemoveUserGroupRoleAsync(group, userRole);
        }
        
        public string DefaultPassword() {
            return base.Channel.DefaultPassword();
        }
        
        public System.Threading.Tasks.Task<string> DefaultPasswordAsync() {
            return base.Channel.DefaultPasswordAsync();
        }
    }
}
